# Site
title: ixSnack.js
subtitle: ixSnack.js Documentation
description: ixSnack.js Documentation
author: blaxk
language: ko
date_format: '%Y-%m-%d'
timezone: 'Asia/Seoul'

# URL
url: http://ixsnack.com
baseurl: /
permalink: /:path/

# Conversion
markdown:    kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /docs/:path/
  examples:
    output: true
    permalink: /examples/:path/

# Default
defaults:
  -
    scope:
      path: 'docs'
      type: 'docs'
    values:
      layout: 'docs'
